# Generated by Django 4.2.7 on 2023-12-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_remove_sasquatch_number_sasquatch_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sasquatch',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
